repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
    
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Hoặc version ổn định mới nhất bạn muốn
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7  # Sử dụng version mới nhất tại thời điểm 2025
    hooks:
      - id: ruff
        args: [--fix]