name: Lint with Ruff

on:
  push:
    branches: ["**"]  # Bất kỳ branch nào
  pull_request:
    branches: ["**"]  # Bất kỳ branch nào

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort black ruff

      - name: Check changed .py files with Isort
        run: isort --check-only .
        # run: |
        #   files=$(git diff --name-only --diff-filter=ACM HEAD^ | grep '\.py$' || true)
        #   if [[ -n "$files" ]]; then
        #     echo "Running: isort --check-only $files"
        #     isort --check-only $files
        #   else
        #     echo "No Python files changed for Isort."
        #   fi

      - name: Check Black
        run: black . --check
        # run: |
        #   files=$(git diff --name-only --diff-filter=ACM HEAD^ | grep '\.py$' || true)
        #   if [[ -n "$files" ]]; then
        #     echo "Running: black --check $files"
        #     black --check $files
        #   else
        #     echo "No Python files changed for Black."
        #   fi

      - name: Run Ruff Check
        run: ruff check .
        # run: |
        #   files=$(git diff --name-only --diff-filter=ACM HEAD^ | grep '\.py$' || true)
        #   if [[ -n "$files" ]]; then
        #     echo "Running: ruff check $files"
        #     ruff check $files
        #   else
        #     echo "No Python files changed for Ruff."
        #   fi